FROM gmazzo/kotlin
COPY src/sync.main.kts /sync.main.kts

ENV SOURCE_GITEA_URL=""
ENV SOURCE_GITEA_TOKEN=""
ENV TARGET_GITEA_URL=""
ENV TARGET_GITEA_TOKEN=""
ENV DRY_RUN="false"
ENV WHITE_LIST_ORGANIZATIONS=""
ENV BLACK_LIST_ORGANIZATIONS=""
ENV WHITE_LIST_REPOSITORIES=""
ENV BLACK_LIST_REPOSITORIES=""

CMD ["/sync.main.kts"]